version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindforge-web
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=mindforgedatabase
      - DATABASE_USER=root
      - DATABASE_PASSWORD=
    command: >
      sh -c "python manage.py migrate &&
             gunicorn mindforge.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: mysql:8.0
    container_name: mindforge-db
    restart: always
    environment:
      MYSQL_DATABASE: mindforgedatabase
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_PASSWORD: ''
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  static_volume:
  media_volume:
