# Generated by Django 4.2.16 on 2024-12-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindforgeApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenido",
            name="archivo",
            field=models.FileField(
                blank=True, null=True, upload_to="media/contenidos/"
            ),
        ),
        migrations.AlterField(
            model_name="entrega",
            name="archivo",
            field=models.FileField(upload_to="media/entregas/"),
        ),
    ]
